name: lint and build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12', '14']
    name: Test with NodeJS ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1.1.0
        with:
          path: node_modules
          key: node_modules
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: run unit tests
        run: yarn test
      - name: Build project
        run: yarn build
