name: e2e

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  end2end-macos:
    runs-on: macos-latest
    name: e2e:safari
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: safari
          start: npm start

  end2end-windows:
    runs-on: windows-latest
    name: e2e:edge
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: edge
          start: npm start

  end2end-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    name: e2e:${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          start: npm start
