name: e2e

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test End2End
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1.1.0
        with:
          path: node_modules
          key: node_modules
      - name: Cache node_modules
        uses: actions/cache@v1.1.0
        with:
          path: ~/.cache
          key: cache
      - name: install cypress dependencies
        run: apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install dependencies
        run: yarn install
      - name: Run e2e in chrome
        run: yarn e2e:chromium
      - name: Run e2e in firefox
        run: yarn e2e:firefox
