name: e2e

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  end2end:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    name: e2e:${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        env:
          MOZ_FORCE_DISABLE_E10S: 1
        with:
          browser: ${{ matrix.browser }}
          start: npm start
