name: e2e

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test End2End
    steps:
      - name: Install dependencies
        run: yarn install
      - name: Start Server
        run: yarn start
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
      - uses: cypress-io/github-action@v2
        with:
          browser: firefox
