# SPDX-FileCopyrightText: 2020 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: build frontend
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache build
        uses: actions/cache@v2.1.3
        with:
          path: build
          key: build

      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn build:test
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  end2end:
    needs: build-frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    name: e2e:${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          start: 'yarn build:serve'
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: screenshots
          path: cypress/screenshots
