name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lints all .ts and .tsx files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1.2.0
        with:
          path: node_modules
          key: node_modules
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn lint
